name: on-dispatch-publish-run-to-npm

on:
  workflow_dispatch:

jobs:
  publish:
    if: github.repository == 'adobe/aio-lib-sandbox'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install
        working-directory: run
      - uses: JS-DevTools/npm-publish@v3
        with:
          package: run/package.json
          token: ${{ secrets.ADOBE_BOT_NPM_TOKEN }}
          access: public
